# Generated by Django 5.1.6 on 2025-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('medical', 'Medical'), ('legal', 'Legal'), ('financial', 'Financial')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text')], default='pdf', max_length=10),
        ),
    ]
