# Generated by Django 5.1.6 on 2025-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_document_category_document_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
