# Generated by Django 5.1.6 on 2025-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_document_highlights_document_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
